version: '3.1'

services:
  ############################
  # Database
  ############################
  delain_db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=delain
      - POSTGRES_DB=delain
    volumes:
      - ../../sql_init:/docker-entrypoint-initdb.d
      - ../../:/home/delain/delain
      - ./conf.php:/home/delain/delain/web/www/includes/conf.php

    container_name: delain_db
    networks:
      - delaintu
  ###############################
  # Serveur web
  ###############################
  web:
    build:
      dockerfile: ./Dockerfile_launch
      context: .
    container_name: web
    networks:
      - delaintu
networks:
  delaintu:
    driver: bridge
 
