version: '3.1'

services:
############################
# Database
############################
  delain_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=delain
      - POSTGRES_DB=delain
    volumes:
      - ../../sql_init:/docker-entrypoint-initdb.d
      - ../../:/home/delain/delain
      - ./conf.php:/home/delain/delain/web/www/includes/conf.php
      # Décommentez la ligne ci dessous si vous voulez
      # garder une database persistante
      # pensez à changer le chemin local
      # - /my/own/datadir:/var/lib/postgresql/data
    container_name: delain_db
###############################
# Serveur web
###############################
  web:
    build: ..
    ports:
      - 9090:80
    container_name: web
    volumes:
    - ../../:/home/delain/delain

 
