version: '3.1'

services:
############################
# Database
############################
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=delain
      - POSTGRES_DB=delain
    volumes:
      - ../sql_init:/docker-entrypoint-initdb.d
      - ../:/home/delain/delain
      # Décommentez la ligne ci dessous si vous voulez
      # garder une database persistante
      # pensez à changer le chemin local
      # - /my/own/datadir:/var/lib/postgresql/data
    container_name: postgres
