version: '3.1'

services:
############################
# Database
############################
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_USER=delain
      - POSTGRES_DB=delain

    volumes:
      - ../sql_init:/docker-entrypoint-initdb.d
      - ../:/home/delain/delain

  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080