name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  prelivraison:
    runs-on: rp


    steps:
      # todo : transformer l'appel à slack qui est un peu long
      - name: Slack notification
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: "Début de livraison"
        uses: rtCamp/action-slack-notify@v2.0.0


      - name: Resume des infos
        if: "!contains(github.event.head_commit.message, 'ci skip')"
        run: |
          echo "Lancement des tests unitaires"
          echo "Répertoire de travail : ${GITHUB_WORKSPACE}"

      - uses: actions/checkout@v2
      - name: lance les tests unitaires

        if: "!contains(github.event.head_commit.message, 'ci skip')"
        run: |
          cd ${GITHUB_WORKSPACE}/
          docker-compose -f docker-compose-tu.yml pull
          docker-compose -f docker-compose-tu.yml up -d
          echo "Wait for postgres to be up"
          docker exec webtu /home/delain/delain/web/tests/wait.sh
          echo 'PHP Unit tests'
          ${GITHUB_WORKSPACE}/web/tests/phpunit_docker-tu.sh
  livraison:
    runs-on: backenddelain
    needs: prelivraison
    steps:
      - name: Git pull
        run: |
          cd /home/delain/delain
          git pull
      - name: Vider le cache
        run: 'rm -rf /home/delain/delain/cache/*'
      - name: Livraisons sql
        run: /home/delain/delain/shell/livraisons.sh
      - name: Generation des docs api
        run: /usr/bin/apidoc -i /home/delain/delain/web/www/api/v2 -o /home/delain/delain/web/www/api/doc
  notif_fin:
    runs-on: rp
    needs: livraison
    steps:
      - name: Slack notification
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: "Fin de livraison"
        uses: rtCamp/action-slack-notify@v2.0.0


