name: CI

# Controls when the action will run. Triggers the workflow on push or pull request

on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test_unitaires:
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    runs-on: rp

    steps:
      - uses: actions/checkout@v2

      - name: Resume des infos
        run: |
          echo "Lancement des tests unitaires"
          echo "Répertoire de travail : ${GITHUB_WORKSPACE}"

      - name: lance les tests unitaires
        run: |
          cd ${GITHUB_WORKSPACE}/
          docker-compose -f docker-compose-tu.yml pull
          docker-compose -f docker-compose-tu.yml up -d
          echo "Wait for postgres to be up"
          docker exec webtu /home/delain/delain/web/tests/wait.sh
          echo 'PHP Unit tests'
          ${GITHUB_WORKSPACE}/web/tests/phpunit_docker-tu.sh



