name: CI
on:
  push:
    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:


  livraison:
    runs-on: ubuntu-latest
    steps:
      - name: Lancement awx
        run: "curl --request POST  --url https://awx.sdewitte.net/api/v2/job_templates/14/launch/  --header 'authorization: Basic ${{ secrets.AUTH_AWX }}'  --cookie __cfduid=d0aa6277fb907532056a58eefe13a568e1598185892"

      - name: Gestion d'erreur
        if: ${{ failure() }}
        uri:
          url: "${{ secrets.SLACK_WEBHOOK2 }}"
          method: POST
          body_format: json
          body: "{\"text\":\" Anomalie sur la livraison (job livraison) \"}"


