name: CI

# Controls when the action will run. Triggers the workflow on push or pull request

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  livraison:
    runs-on: rp
    steps:
      - uses: actions/checkout@v2
      # todo : transformer l'appel à slack qui est un peu long
      - name: Slack notification
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: "Début de livraison"
        uses: rtCamp/action-slack-notify@v2.0.0


      - name: Resume des infos
        if: "!contains(github.event.head_commit.message, 'ci skip')"
        run: |
          echo "Lancement des tests unitaires"
          echo "Répertoire de travail : ${GITHUB_WORKSPACE}"

      - name: lance les tests unitaires
        if: "!contains(github.event.head_commit.message, 'ci skip')"
        run: |
          cd ${GITHUB_WORKSPACE}/
          docker-compose -f docker-compose-tu.yml pull
          docker-compose -f docker-compose-tu.yml up -d
          echo "Wait for postgres to be up"
          docker exec webtu /home/delain/delain/web/tests/wait.sh
          echo 'PHP Unit tests'
          ${GITHUB_WORKSPACE}/web/tests/phpunit_docker-tu.sh
      - name: Slack notification
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: "Fin de livraison"
        uses: rtCamp/action-slack-notify@v2.0.0




  #livraison:
  #  needs: notif_debut
  #  runs-on: backenddelain
  #  steps:
  #    - name: git pull
  #      run : |
  #        cd /home/delain/delain
  #        git pull
  #    - name: empty cache
  #      run: 'rm -rf /home/delain/delain/cache/*'
  #    - name: Livraisons sql
  #      run: /home/delain/delain/shell/livraisons.sh
  #    - name: Generation des docs api
  #      run: /usr/bin/apidoc -i /home/delain/delain/web/www/api/v2 -o /home/delain/delain/web/www/api/doc